# Constraint diagnostics --------------------------------------------------

compute_constraint_diagnostics <- function(fit) {
  validate_ffp_fit(fit)

  constraints <- fit$constraints
  metadata <- constraints$metadata
  posterior <- fit$posterior
  tolerance <- fit$solver$control$constraint_tolerance

  n_constraints <- nrow(metadata)

  lhs <- rep(NA_real_, n_constraints)
  rhs <- rep(NA_real_, n_constraints)
  gap <- rep(NA_real_, n_constraints)

  residual <- rep(NA_real_, n_constraints)
  slack <- rep(NA_real_, n_constraints)
  violation <- rep(NA_real_, n_constraints)

  binding <- rep(NA, n_constraints)
  satisfied <- rep(FALSE, n_constraints)

  equality <- metadata$constraint_type == "equality"
  inequality <- metadata$constraint_type == "inequality"

  if (any(equality)) {
    rows <- metadata$constraint_row[equality]

    lhs[equality] <- drop(
      constraints$a_eq[rows, , drop = FALSE] %*% posterior
    )

    rhs[equality] <- constraints$b_eq[rows]
    gap[equality] <- lhs[equality] - rhs[equality]

    residual[equality] <- abs(gap[equality])
    satisfied[equality] <- residual[equality] <= tolerance
  }

  if (any(inequality)) {
    rows <- metadata$constraint_row[inequality]

    lhs[inequality] <- drop(
      constraints$a_ineq[rows, , drop = FALSE] %*% posterior
    )

    rhs[inequality] <- constraints$b_ineq[rows]
    gap[inequality] <- lhs[inequality] - rhs[inequality]

    slack[inequality] <- rhs[inequality] - lhs[inequality]
    violation[inequality] <- pmax(gap[inequality], 0)

    binding[inequality] <- abs(slack[inequality]) <= tolerance
    satisfied[inequality] <- violation[inequality] <= tolerance
  }

  tibble::tibble(
    view_id = metadata$view_index,
    constraint_id = metadata$view_constraint_index,
    method = metadata$method,
    feature_1 = metadata$feature_1,
    feature_2 = metadata$feature_2,
    condition = metadata$condition,
    constraint_type = metadata$constraint_type,
    constraint = metadata$label,
    lhs = lhs,
    rhs = rhs,
    gap = gap,
    residual = residual,
    slack = slack,
    violation = violation,
    binding = binding,
    satisfied = satisfied
  )
}


# View diagnostics --------------------------------------------------------

compute_view_diagnostics <- function(fit) {
  validate_ffp_fit(fit)

  n_views <- fit$n_views

  if (n_views == 0L) {
    return(
      tibble::tibble(
        view_id = integer(),
        method = character(),
        expression = character(),
        n_constraints = integer(),
        n_equalities = integer(),
        n_inequalities = integer(),
        n_binding = integer(),
        max_error = double(),
        status = character()
      )
    )
  }

  constraints <- compute_constraint_diagnostics(fit)

  diagnostics <- lapply(
    seq_len(n_views),
    function(i) {
      view <- fit$model$views[[i]]
      block <- constraints[constraints$view_id == i, , drop = FALSE]

      equality <- block$constraint_type == "equality"
      inequality <- block$constraint_type == "inequality"

      errors <- c(
        block$residual[equality],
        block$violation[inequality]
      )

      max_error <- if (length(errors) == 0L) {
        0
      } else {
        max(errors)
      }

      tibble::tibble(
        view_id = as.integer(i),
        method = view$method,
        expression = view$metadata$expression,
        n_constraints = as.integer(nrow(block)),
        n_equalities = as.integer(sum(equality)),
        n_inequalities = as.integer(sum(inequality)),
        n_binding = as.integer(sum(block$binding, na.rm = TRUE)),
        max_error = max_error,
        status = if (all(block$satisfied)) "satisfied" else "violated"
      )
    }
  )

  do.call(rbind, diagnostics)

}


# Public interface --------------------------------------------------------

#' Diagnose a fitted FFP model
#'
#' `ffp_diagnostics()` summarizes how the views in an [ffp_fit] object are
#' represented and satisfied by the fitted posterior probabilities.
#'
#' By default, diagnostics are reported at the semantic view level, with one
#' row for each view added through [ffp_view()]. Advanced users can request the
#' underlying mathematical constraints with `level = "constraint"`.
#'
#' @param fit An [ffp_fit] object.
#' @param level Diagnostic level. `"view"` returns one row per semantic view.
#'   `"constraint"` returns one row per compiled mathematical constraint.
#'
#' @return A tibble.
#'
#' With `level = "view"`, the tibble contains:
#'
#' - `view_id`: position of the view in the fitted model;
#' - `method`: view method;
#' - `expression`: expression originally used to define the view;
#' - `n_constraints`: number of mathematical constraints generated by the view;
#' - `n_equalities`: number of equality constraints;
#' - `n_inequalities`: number of inequality constraints;
#' - `n_binding`: number of inequality constraints that are numerically binding;
#' - `max_error`: largest equality residual or inequality violation;
#' - `status`: `"satisfied"` when all constraints are satisfied within the
#'   solver tolerance, otherwise `"violated"`.
#'
#' With `level = "constraint"`, the tibble contains one row per compiled
#' mathematical constraint together with its metadata and numerical
#' diagnostics.
#'
#' @details
#' A semantic view may generate more than one mathematical constraint. For
#' example, each quantile target produces two inequalities, while covariance
#' and correlation views may generate several equality constraints.
#'
#' The default view-level output keeps these implementation details aggregated
#' so that diagnostics remain aligned with the views specified by the user.
#'
#' At the constraint level, `lhs` and `rhs` refer to the compiled mathematical
#' constraint. They should not necessarily be interpreted as the original
#' user-facing target. Some view types, such as conditional probabilities,
#' volatility, covariance, and correlation, are transformed into equivalent
#' linear constraints during compilation.
#'
#' Equality constraints report:
#'
#' - `gap = lhs - rhs`;
#' - `residual = abs(gap)`.
#'
#' Inequality constraints are represented as `lhs <= rhs` and report:
#'
#' - `gap = lhs - rhs`;
#' - `slack = rhs - lhs`;
#' - `violation = max(lhs - rhs, 0)`;
#' - `binding`, indicating whether the absolute slack is within the
#'   `constraint_tolerance` used when the model was fitted.
#'
#' Equality constraints do not have a meaningful binding status, so `binding`
#' is `NA` for equalities.
#'
#' The numerical tolerance used by the diagnostics is the tolerance stored in
#' the fitted solver result. Calling `ffp_diagnostics()` therefore does not
#' reinterpret an existing fit using the package's current default tolerance.
#'
#' @examples
#' scenarios <- data.frame(
#'   equity = c(-0.08, -0.03, 0.01, 0.04, 0.06),
#'   inflation = c(0.02, 0.03, 0.035, 0.045, 0.05)
#' )
#'
#' model <- ffp_model(scenarios) |>
#'   ffp_prior(
#'     prior_uniform()
#'   ) |>
#'   ffp_view(
#'     view_mean(
#'       equity,
#'       target = 0.02
#'     ),
#'     view_quantile(
#'       inflation,
#'       target = 0.045,
#'       level = 0.80
#'     )
#'   )
#'
#' fit <- ffp_fit(model)
#'
#' # One row per semantic view
#' ffp_diagnostics(fit)
#'
#' # One row per compiled mathematical constraint
#' ffp_diagnostics(
#'   fit,
#'   level = "constraint"
#' )
#'
#' @seealso [ffp_fit()], [ffp_probabilities()]
#'
#' @export
ffp_diagnostics <- function(fit, level = c("view", "constraint")) {

  validate_ffp_fit(fit)
  level <- match.arg(level)

  if (identical(level, "constraint")) {
    return(compute_constraint_diagnostics(fit))
  }

  compute_view_diagnostics(fit)

}
